services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: southamerica-east1-docker.pkg.dev/build-with-ai-2025-461020/cloud-run-repo/build_with_ai:0.0.1
    env_file:
      - .env
    ports:
      - "8000:8000"
